services:
  wordpress:
    depends_on:
      - database
    image: wordpress # Using the official WordPress image
    ports:
      - 8000:80 # Mapping port 80 of the host to port 80 of the container
    environment:
      # Environment variables for WordPress to connect to the database
      WORDPRESS_DB_HOST: '${MYSQL_HOST}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content # Mapping the wp-content directory for persistence

  database:
    image: mysql:latest # Using the latest official MySQL image
    ports:
      - 3306:3306 # Mapping port 3306 of the host to port 3306 of the container
    environment:
      # Environment variables for MySQL configuration
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql # Mapping the MySQL data directory for persistence

volumes:
  mysql-data: # Named volume for MySQL data
