services:
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: "${MYSQL_HOST}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8000');
        define('WP_SITEURL', 'http://localhost:8000');
        define('WP_DEFAULT_THEME', 'empty-theme');
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
      - wordpress-data:/var/www/html
    command: sh -c "rm -rf /var/www/html/wp-content/themes/twenty* && docker-entrypoint.sh apache2-foreground"

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  wordpress-data:
